### ISSUE TITLE
是否支持上下问的情景，能否给个样例

### ISSUE THREAD

**Issue by cmdares** [chatopera/conversation-sampleapp#2]
如题，希望构建含有上下午的情景对话
问：杭州天津如何
答：多云
问：适合去什么地方游玩
答：公园或者乐园
问：公园可以去哪
答：可以去西湖转转
像是这种带有上下文语义的情景对话平台是否可以支持。可以做个例子示范下吗，谢谢。

**Comment by Samurais** [comment]
这里是匹配上文的城市，然后取空气质量。

https://github.com/chatopera/conversation-sampleapp/blob/4b7eb89ed9565611717e5f451a98caf4f50b3a57/app/zh_CN.weather.ms#L28

使用 % 进行上文规则匹配，使用 p1capN进行上文的槽位信息获取。
